//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Cycle.
        /// </summary>
        public static string CreateCycleWindowButtonCreateCycle {
            get {
                return ResourceManager.GetString("CreateCycleWindowButtonCreateCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose how the cycle will be created:.
        /// </summary>
        public static string CreateCycleWindowLabelChooseCycle {
            get {
                return ResourceManager.GetString("CreateCycleWindowLabelChooseCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the wanted function.
        /// </summary>
        public static string CreateCycleWindowLabelWarning {
            get {
                return ResourceManager.GetString("CreateCycleWindowLabelWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Cycle Count.
        /// </summary>
        public static string CreateCycleWindowTitle {
            get {
                return ResourceManager.GetString("CreateCycleWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string EditCycleWindowButtonCancel {
            get {
                return ResourceManager.GetString("EditCycleWindowButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string EditCycleWindowButtonConfirm {
            get {
                return ResourceManager.GetString("EditCycleWindowButtonConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Cycle.
        /// </summary>
        public static string EditCycleWindowButtonDeleteCycle {
            get {
                return ResourceManager.GetString("EditCycleWindowButtonDeleteCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete users work.
        /// </summary>
        public static string EditCycleWindowButtonDeleteUser {
            get {
                return ResourceManager.GetString("EditCycleWindowButtonDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move down.
        /// </summary>
        public static string EditCycleWindowButtonMoveDown {
            get {
                return ResourceManager.GetString("EditCycleWindowButtonMoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move up.
        /// </summary>
        public static string EditCycleWindowButtonMoveUp {
            get {
                return ResourceManager.GetString("EditCycleWindowButtonMoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete a specific users changes:.
        /// </summary>
        public static string EditCycleWindowLabelChooseUsers {
            get {
                return ResourceManager.GetString("EditCycleWindowLabelChooseUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the cycle.
        /// </summary>
        public static string EditCycleWindowLabelDeleteCycle {
            get {
                return ResourceManager.GetString("EditCycleWindowLabelDeleteCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose how to modify the cycle:.
        /// </summary>
        public static string EditCycleWindowLabelEditType {
            get {
                return ResourceManager.GetString("EditCycleWindowLabelEditType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose how the shelves are sorted:.
        /// </summary>
        public static string EditCycleWindowLabelPriority {
            get {
                return ResourceManager.GetString("EditCycleWindowLabelPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a user:.
        /// </summary>
        public static string EditCycleWindowLabelWarning {
            get {
                return ResourceManager.GetString("EditCycleWindowLabelWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Cycle.
        /// </summary>
        public static string EditCycleWindowTitle {
            get {
                return ResourceManager.GetString("EditCycleWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string LogWindowButtonSearch {
            get {
                return ResourceManager.GetString("LogWindowButtonSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string LogWindowHeaderMessage {
            get {
                return ResourceManager.GetString("LogWindowHeaderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string LogWindowHeaderTime {
            get {
                return ResourceManager.GetString("LogWindowHeaderTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User id.
        /// </summary>
        public static string LogWindowHeaderUser {
            get {
                return ResourceManager.GetString("LogWindowHeaderUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages after:.
        /// </summary>
        public static string LogWindowLabelAfter {
            get {
                return ResourceManager.GetString("LogWindowLabelAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages before:.
        /// </summary>
        public static string LogWindowLabelBefore {
            get {
                return ResourceManager.GetString("LogWindowLabelBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item id:.
        /// </summary>
        public static string LogWindowLabelItem {
            get {
                return ResourceManager.GetString("LogWindowLabelItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location id:.
        /// </summary>
        public static string LogWindowLabelLocation {
            get {
                return ResourceManager.GetString("LogWindowLabelLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User id:.
        /// </summary>
        public static string LogWindowLabelUser {
            get {
                return ResourceManager.GetString("LogWindowLabelUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string LogWindowTitle {
            get {
                return ResourceManager.GetString("LogWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Cycle Count.
        /// </summary>
        public static string MainWindowButtonCreateCycle {
            get {
                return ResourceManager.GetString("MainWindowButtonCreateCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Cycle.
        /// </summary>
        public static string MainWindowButtonEditCycle {
            get {
                return ResourceManager.GetString("MainWindowButtonEditCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish Cycle.
        /// </summary>
        public static string MainWindowButtonFinishCycle {
            get {
                return ResourceManager.GetString("MainWindowButtonFinishCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string MainWindowButtonShowChosenType {
            get {
                return ResourceManager.GetString("MainWindowButtonShowChosenType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show log.
        /// </summary>
        public static string MainWindowButtonShowLog {
            get {
                return ResourceManager.GetString("MainWindowButtonShowLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Language.
        /// </summary>
        public static string MainWindowButtonSwitchLanguage {
            get {
                return ResourceManager.GetString("MainWindowButtonSwitchLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counted with difference:.
        /// </summary>
        public static string MainWindowComboboxCountedDifference {
            get {
                return ResourceManager.GetString("MainWindowComboboxCountedDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counted in this cycle.
        /// </summary>
        public static string MainWindowComboboxCountedThisCycle {
            get {
                return ResourceManager.GetString("MainWindowComboboxCountedThisCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counted today.
        /// </summary>
        public static string MainWindowComboboxCountedToday {
            get {
                return ResourceManager.GetString("MainWindowComboboxCountedToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Difference.
        /// </summary>
        public static string MainWindowHeaderCountVariance {
            get {
                return ResourceManager.GetString("MainWindowHeaderCountVariance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Counted.
        /// </summary>
        public static string MainWindowHeaderHasBeenCounted {
            get {
                return ResourceManager.GetString("MainWindowHeaderHasBeenCounted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ID.
        /// </summary>
        public static string MainWindowHeaderId {
            get {
                return ResourceManager.GetString("MainWindowHeaderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Locations.
        /// </summary>
        public static string MainWindowHeaderLocations {
            get {
                return ResourceManager.GetString("MainWindowHeaderLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Name.
        /// </summary>
        public static string MainWindowHeaderName {
            get {
                return ResourceManager.GetString("MainWindowHeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Counted from server.
        /// </summary>
        public static string MainWindowHeaderServerCount {
            get {
                return ResourceManager.GetString("MainWindowHeaderServerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Counted from storage.
        /// </summary>
        public static string MainWindowHeaderStorageCount {
            get {
                return ResourceManager.GetString("MainWindowHeaderStorageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active clients:.
        /// </summary>
        public static string MainWindowLabelActiveClients {
            get {
                return ResourceManager.GetString("MainWindowLabelActiveClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total counted:.
        /// </summary>
        public static string MainWindowLabelTotalCount {
            get {
                return ResourceManager.GetString("MainWindowLabelTotalCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counted with difference:.
        /// </summary>
        public static string MainWindowLabelTotalCountDifference {
            get {
                return ResourceManager.GetString("MainWindowLabelTotalCountDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose the desired function.
        /// </summary>
        public static string MainWindowLabelWarning {
            get {
                return ResourceManager.GetString("MainWindowLabelWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string PhoneAdminLoginButtonBack {
            get {
                return ResourceManager.GetString("PhoneAdminLoginButtonBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string PhoneAdminLoginStackLayoutEntryUserName {
            get {
                return ResourceManager.GetString("PhoneAdminLoginStackLayoutEntryUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User password.
        /// </summary>
        public static string PhoneAdminLoginStackLayoutEntryUserPW {
            get {
                return ResourceManager.GetString("PhoneAdminLoginStackLayoutEntryUserPW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Login.
        /// </summary>
        public static string PhoneAdminLoginStackLayoutLabelAdminLogin {
            get {
                return ResourceManager.GetString("PhoneAdminLoginStackLayoutLabelAdminLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your password:.
        /// </summary>
        public static string PhoneAdminLoginStackLayoutLabelEnterPW {
            get {
                return ResourceManager.GetString("PhoneAdminLoginStackLayoutLabelEnterPW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth Scan.
        /// </summary>
        public static string PhoneAdminStartPageButtonBTScan {
            get {
                return ResourceManager.GetString("PhoneAdminStartPageButtonBTScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Scan.
        /// </summary>
        public static string PhoneAdminStartPageButtonCameraScan {
            get {
                return ResourceManager.GetString("PhoneAdminStartPageButtonCameraScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string PhoneAdminStartPageButtonLogOut {
            get {
                return ResourceManager.GetString("PhoneAdminStartPageButtonLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanner.
        /// </summary>
        public static string PhoneAdminStartPageLabelScanner {
            get {
                return ResourceManager.GetString("PhoneAdminStartPageLabelScanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add item.
        /// </summary>
        public static string PhoneInventoryPageButtonAddItem {
            get {
                return ResourceManager.GetString("PhoneInventoryPageButtonAddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove item.
        /// </summary>
        public static string PhoneInventoryPageButtonRemoveItem {
            get {
                return ResourceManager.GetString("PhoneInventoryPageButtonRemoveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage item location:.
        /// </summary>
        public static string PhoneInventoryPageLabelManageLocation {
            get {
                return ResourceManager.GetString("PhoneInventoryPageLabelManageLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MENU.
        /// </summary>
        public static string PhoneInventoryPageLabelMenu {
            get {
                return ResourceManager.GetString("PhoneInventoryPageLabelMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string PhoneLocationSelectedButtonMenu {
            get {
                return ResourceManager.GetString("PhoneLocationSelectedButtonMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string PhoneLocationSelelectButtonLight {
            get {
                return ResourceManager.GetString("PhoneLocationSelelectButtonLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Login.
        /// </summary>
        public static string PhoneMainPageButtonAdmin {
            get {
                return ResourceManager.GetString("PhoneMainPageButtonAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth Scan.
        /// </summary>
        public static string PhoneMainPageButtonBTScan {
            get {
                return ResourceManager.GetString("PhoneMainPageButtonBTScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Scan.
        /// </summary>
        public static string PhoneMainPageButtonCameraScan {
            get {
                return ResourceManager.GetString("PhoneMainPageButtonCameraScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCANNER.
        /// </summary>
        public static string PhoneMainPageLabelScanner {
            get {
                return ResourceManager.GetString("PhoneMainPageLabelScanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string PhoneStartPageButtonBack {
            get {
                return ResourceManager.GetString("PhoneStartPageButtonBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Login.
        /// </summary>
        public static string PhoneStartPageButtonLogin {
            get {
                return ResourceManager.GetString("PhoneStartPageButtonLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch scan type.
        /// </summary>
        public static string PhoneStartPageButtonSwitch {
            get {
                return ResourceManager.GetString("PhoneStartPageButtonSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminate Scan.
        /// </summary>
        public static string PhoneStartPageButtonTerminate {
            get {
                return ResourceManager.GetString("PhoneStartPageButtonTerminate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload data.
        /// </summary>
        public static string PhoneStartPageButtonUpload {
            get {
                return ResourceManager.GetString("PhoneStartPageButtonUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MENU.
        /// </summary>
        public static string PhoneStartPageLabelMenu {
            get {
                return ResourceManager.GetString("PhoneStartPageLabelMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Partition.
        /// </summary>
        public static string PhoneUploadDataButtonDownload {
            get {
                return ResourceManager.GetString("PhoneUploadDataButtonDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Partition.
        /// </summary>
        public static string PhoneUploadDataButtonUpload {
            get {
                return ResourceManager.GetString("PhoneUploadDataButtonUpload", resourceCulture);
            }
        }
    }
}
